### ISSUE TITLE
Broken login url

### ISSUE THREAD

**Issue by hmorrin** [NSAMR/nsamr.ac.uk#10]
Attempting to access nsamr.ac.uk/wp-admin results in too many redirection attempts @nsamr-it

**Comment by DeckOfPandas** [comment]
Ta

NB: Detail is gooooood because who knows when I'll get to this. Also,
someone else might fix it... </optimism>

>

**Comment by DeckOfPandas** [comment]
You can also tag users like this @hmorrin @rmlundin

**Comment by DeckOfPandas** [comment]
Fixed for now

Main site: http://www.nsamr.ac.uk/site
Journal index: http://www.nsamr.ac.uk/journal/journal-index
Journal machinery: http://www.nsamr.ac.uk/journal/journal-machinery

We can tidy up all the URLs at the end of v0
